Adds screen reader text to pagination - trello ticket #463
ministryofjustice/wp-justicejobs pull request #10
Opened 2019-12-23 13:49 UTC by BNewing

This adds text to the pagination links. I've added text to the previous and next links as well as the numbers.

2019-12-27 16:03 UTC, wilson1000-MoJ requested changes

2019-12-27 16:03 UTC, wilson1000-MoJ commented on web/app/themes/justicejobs/search-apply-page.php
> +            'after_page_number' => '<span class="screen-reader-text"> of ' . __( $job_query->max_num_pages ). '</span>'
__() is a WP translation function used to display (if present) the text in a different language.
It is best practice to define a text-domain in the themes root style.css file and then pass the text-domain as a string in the second parameter in each function call. This is regarded as good code development as it essentially creates a theme translation layer and will make translation processes easier in future. 
Would you kindly add the text-domain?
Ref: https://developer.wordpress.org/reference/functions/__/

2019-12-27 16:03 UTC, wilson1000-MoJ commented on web/app/themes/justicejobs/search-apply-page.php
> +            'after_page_number' => '<span class="screen-reader-text"> of ' . __( $job_query->max_num_pages ). '</span>'
As above

2019-12-27 16:03 UTC, wilson1000-MoJ commented on web/app/themes/justicejobs/search.php
> +                    'after_page_number' => '<span class="screen-reader-text"> of ' . __( $job_query->max_num_pages ). '</span>'
Add text-domain to __()

2019-12-27 16:03 UTC, wilson1000-MoJ commented on web/app/themes/justicejobs/search.php
> +                    'after_page_number' => '<span class="screen-reader-text"> of ' . __( $job_query->max_num_pages ). '</span>'
Add text-domain to __()

2019-12-30 12:26 UTC, BNewing commented
Thank you for the change requests @wilson1000-MoJ ! I've now added another commit to address this feedback

2019-12-31 12:44 UTC, merged